/**
 * 45 Comprehensive Indian Tech Engineering Profiles
 * Represents realistic engineering workforce across Bangalore, Hyderabad, Pune, Gurgaon, Noida, Chennai, and Mumbai tech hubs.
 */

const HUBS = [
  'Bangalore Tech Hub (Bellandur)',
  'Bangalore Tech Hub (Whitefield)',
  'Hyderabad Innovation Hub (HITEC City)',
  'Pune Engineering Center (Hinjawadi)',
  'Gurgaon Cyber City (DLF Phase 2)',
  'Noida Tech Zone (Sector 62)',
  'Chennai IT Corridor (OMR)'
];

export const INDIAN_ENGINEERING_SAMPLES = [
  // ─── 1. LEADERSHIP & ARCHITECTURE (1 - 5) ─────────────────────────────────
  {
    code: 'EMP-IND-101',
    firstName: 'Priya',
    lastName: 'Sharma',
    workEmail: 'priya.sharma@company.com',
    designation: 'Lead Distributed Systems Architect',
    department: 'Engineering',
    location: 'Bangalore, KA (Hybrid)',
    headline: 'Lead Distributed Systems Architect | Ex-Razorpay & Swiggy | IIT Delhi',
    summary: '8.5+ years designing ultra-scalable distributed event streams and payment gateways. Specializes in low-latency Go/Kafka systems processing 50k+ peak TPS.',
    totalExperienceYears: 8.5,
    currentLocation: 'Bangalore, Karnataka, India',
    githubUrl: 'https://github.com/priya-sharma-dev',
    linkedinUrl: 'https://linkedin.com/in/priya-sharma-systems',
    skills: [
      { name: 'Go (Golang)', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.98, verificationStatus: 'VERIFIED' },
      { name: 'Apache Kafka', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 5, source: 'MANAGER_VERIFIED', confidence: 0.96, verificationStatus: 'VERIFIED' },
      { name: 'Distributed Systems', category: 'ARCHITECTURE', proficiency: 'Expert', yearsOfExperience: 7, source: 'MANAGER_VERIFIED', confidence: 0.95, verificationStatus: 'VERIFIED' },
      { name: 'PostgreSQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 7, source: 'SELF_REPORTED', confidence: 0.92, verificationStatus: 'VERIFIED' },
      { name: 'Kubernetes', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, source: 'AI_EXTRACTED', confidence: 0.88, verificationStatus: 'VERIFIED' },
      { name: 'AWS Cloud Architecture', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.94, verificationStatus: 'VERIFIED' },
      { name: 'Redis Caching', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, source: 'SELF_REPORTED', confidence: 0.90, verificationStatus: 'VERIFIED' },
      { name: 'gRPC & Protocol Buffers', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, source: 'SELF_REPORTED', confidence: 0.89, verificationStatus: 'VERIFIED' }
    ],
    experience: [
      { title: 'Staff Software Engineer', company: 'Razorpay India', location: 'Bangalore, KA', startDate: '2021-06-01', endDate: '2023-10-31', current: false, description: 'Re-architected UPI transaction settlement pipeline handling ₹800Cr+ monthly processing with 99.999% uptime.', technologies: ['Go', 'Kafka', 'PostgreSQL', 'AWS EKS', 'Redis'] },
      { title: 'Senior Backend Engineer', company: 'Swiggy', location: 'Bangalore, KA', startDate: '2018-08-01', endDate: '2021-05-31', current: false, description: 'Built geo-spatial delivery routing engine reducing order dispatch latency by 35%.', technologies: ['Java', 'Spring Boot', 'Kafka', 'Cassandra'] }
    ],
    projects: [
      { name: 'Nexus Real-Time Event Bus', role: 'Principal Architect & Lead', description: 'Built zero-data-loss streaming backbone uniting attendance, payroll and hiring events into asynchronous event streams.', technologies: ['Go', 'Kafka', 'Schema Registry', 'Docker'], duration: '8 Months', impact: 'Reduced inter-service API polling by 70% and eliminated race conditions.' }
    ],
    certifications: [
      { name: 'AWS Certified Solutions Architect – Professional', issuer: 'Amazon Web Services', issueDate: '2023-04-10', credentialId: 'AWS-SAP-882194', verificationStatus: 'VERIFIED' },
      { name: 'Certified Kubernetes Administrator (CKA)', issuer: 'Linux Foundation / CNCF', issueDate: '2022-09-15', credentialId: 'CKA-2200-9182', verificationStatus: 'VERIFIED' }
    ],
    careerPreferences: { desiredRoles: ['Director of Core Engineering', 'Principal Platform Architect'], targetSkills: ['Rust Programming', 'Distributed Consensus (Raft/Paxos)', 'eBPF Kernel Tracing'], interestDomains: ['High-Frequency FinTech', 'Cloud Infrastructure Platforms'], willingToRelocate: false, preferredWorkMode: 'HYBRID' }
  },
  {
    code: 'EMP-IND-102',
    firstName: 'Amit',
    lastName: 'Kumar',
    workEmail: 'amit.kumar@company.com',
    designation: 'Principal Frontend Architect',
    department: 'Engineering',
    location: 'Bangalore, KA (Hybrid)',
    headline: 'Principal Frontend Architect | Ex-Flipkart & CureFit | Web Performance & Design Systems',
    summary: '7+ years leading web application performance, micro-frontends, design systems, and glassmorphic UI engineering.',
    totalExperienceYears: 7.2,
    currentLocation: 'Bangalore, Karnataka, India',
    githubUrl: 'https://github.com/amitkumar-fe',
    linkedinUrl: 'https://linkedin.com/in/amit-kumar-ui',
    skills: [
      { name: 'React.js', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 7, source: 'MANAGER_VERIFIED', confidence: 0.99, verificationStatus: 'VERIFIED' },
      { name: 'TypeScript', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, source: 'MANAGER_VERIFIED', confidence: 0.97, verificationStatus: 'VERIFIED' },
      { name: 'Next.js & SSR', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 4, source: 'SELF_REPORTED', confidence: 0.94, verificationStatus: 'VERIFIED' },
      { name: 'Design Systems & CSS Architecture', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.95, verificationStatus: 'VERIFIED' },
      { name: 'Web Core Vitals & Performance', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, source: 'MANAGER_VERIFIED', confidence: 0.96, verificationStatus: 'VERIFIED' }
    ],
    experience: [
      { title: 'Lead Frontend Engineer', company: 'Flipkart Internet', location: 'Bangalore, KA', startDate: '2020-04-01', endDate: '2023-08-31', current: false, description: 'Owned the Big Billion Days checkout & cart micro-frontend, achieving 98+ Lighthouse scores across 100M+ visitors.', technologies: ['React', 'TypeScript', 'Webpack Module Federation', 'Web Vitals'] }
    ],
    projects: [
      { name: 'Nexus Glassmorphic Design System', role: 'Frontend Architect', description: 'Custom React & Vanilla CSS component design system with zero runtime CSS overhead.', technologies: ['React', 'TypeScript', 'CSS Variables', 'Vite'], duration: '6 Months', impact: 'Cut frontend bundle size by 45%.' }
    ],
    certifications: [
      { name: 'Meta Certified Front-End Developer', issuer: 'Meta / Coursera', issueDate: '2022-03-20', credentialId: 'META-FE-71029', verificationStatus: 'VERIFIED' }
    ],
    careerPreferences: { desiredRoles: ['VP of Frontend Engineering', 'Head of Product Design & Tech'], targetSkills: ['WebAssembly (Wasm)', 'Three.js 3D Visualizations'], interestDomains: ['Design Systems', 'Data-Intensive Dashboards'], willingToRelocate: false, preferredWorkMode: 'HYBRID' }
  },
  {
    code: 'EMP-IND-103',
    firstName: 'Rajesh',
    lastName: 'Varma',
    workEmail: 'rajesh.varma@company.com',
    designation: 'Staff Platform & DevOps Lead',
    department: 'Platform & DevOps',
    location: 'Hyderabad, TS (Hybrid)',
    headline: 'Staff Platform & DevOps Lead | Ex-Flipkart & Microsoft India | Cloud Infrastructure & SRE',
    summary: '9+ years architecting multi-region Kubernetes clusters, GitOps pipelines, Terraform IaC, and 99.99% cloud resiliency.',
    totalExperienceYears: 9.0,
    currentLocation: 'Hyderabad, Telangana, India',
    githubUrl: 'https://github.com/rajesh-varma-devops',
    linkedinUrl: 'https://linkedin.com/in/rajesh-varma-cloud',
    skills: [
      { name: 'Kubernetes (EKS/GKE)', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.99, verificationStatus: 'VERIFIED' },
      { name: 'Terraform & OpenTofu IaC', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 5, source: 'MANAGER_VERIFIED', confidence: 0.97, verificationStatus: 'VERIFIED' },
      { name: 'AWS Cloud Services', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 8, source: 'MANAGER_VERIFIED', confidence: 0.98, verificationStatus: 'VERIFIED' },
      { name: 'Docker & Containers', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 7, source: 'SELF_REPORTED', confidence: 0.95, verificationStatus: 'VERIFIED' },
      { name: 'CI/CD Pipelines (ArgoCD)', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.96, verificationStatus: 'VERIFIED' }
    ],
    experience: [
      { title: 'Senior DevOps Architect', company: 'Microsoft IDC India', location: 'Hyderabad, TS', startDate: '2019-03-01', endDate: '2023-05-31', current: false, description: 'Led cloud migration of 120+ microservices to Azure Kubernetes Service.', technologies: ['Kubernetes', 'Terraform', 'Azure DevOps', 'ArgoCD'] }
    ],
    projects: [
      { name: 'Nexus Infrastructure As Code', role: 'Platform Lead', description: 'Automated zero-downtime blue/green deployment orchestration across AWS Mumbai.', technologies: ['Terraform', 'AWS EKS', 'ArgoCD'], duration: '12 Months', impact: 'Reduced rollback duration to under 30s.' }
    ],
    certifications: [
      { name: 'AWS Certified DevOps Engineer – Professional', issuer: 'Amazon Web Services', issueDate: '2023-08-01', credentialId: 'AWS-DOP-49102', verificationStatus: 'VERIFIED' },
      { name: 'Certified Kubernetes Security Specialist (CKS)', issuer: 'CNCF', issueDate: '2023-01-15', credentialId: 'CKS-990-213', verificationStatus: 'VERIFIED' }
    ],
    careerPreferences: { desiredRoles: ['Head of Cloud Infrastructure & SRE', 'VP of Platform Engineering'], targetSkills: ['Service Mesh (Istio Ambient)', 'FinOps Cloud Cost Governance'], interestDomains: ['Platform Engineering', 'Zero-Trust Security'], willingToRelocate: true, preferredWorkMode: 'HYBRID' }
  },
  {
    code: 'EMP-IND-104',
    firstName: 'Ananya',
    lastName: 'Iyer',
    workEmail: 'ananya.iyer@company.com',
    designation: 'Lead AI/ML & GenAI Scientist',
    department: 'AI Research & Data',
    location: 'Pune, MH (Hybrid)',
    headline: 'Lead AI/ML & GenAI Scientist | Ex-Zomato ML Labs & IISc Bangalore | LLMs & NLP',
    summary: '6+ years in applied Natural Language Processing, Hugging Face transformers, RAG architectures, and predictive analytics.',
    totalExperienceYears: 6.0,
    currentLocation: 'Pune, Maharashtra, India',
    githubUrl: 'https://github.com/ananya-iyer-ai',
    linkedinUrl: 'https://linkedin.com/in/ananya-iyer-ml',
    skills: [
      { name: 'Python', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 6, source: 'MANAGER_VERIFIED', confidence: 0.99, verificationStatus: 'VERIFIED' },
      { name: 'PyTorch & Transformers', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, source: 'MANAGER_VERIFIED', confidence: 0.97, verificationStatus: 'VERIFIED' },
      { name: 'Large Language Models (LLMs)', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 3, source: 'MANAGER_VERIFIED', confidence: 0.98, verificationStatus: 'VERIFIED' },
      { name: 'Vector Databases (Qdrant/Pinecone)', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 2, source: 'SELF_REPORTED', confidence: 0.92, verificationStatus: 'VERIFIED' },
      { name: 'FastAPI Backend Serving', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, source: 'SELF_REPORTED', confidence: 0.91, verificationStatus: 'VERIFIED' }
    ],
    experience: [
      { title: 'Senior ML Engineer', company: 'Zomato ML Labs', location: 'Gurgaon, HR', startDate: '2021-02-01', endDate: '2023-09-30', current: false, description: 'Built customer sentiment analysis and intent detection NLP pipelines serving 10M+ interactions daily.', technologies: ['PyTorch', 'BERT', 'FastAPI', 'Ray Serve'] }
    ],
    projects: [
      { name: 'Nexus Skill Extraction & Match Engine', role: 'AI Lead', description: 'Built Hugging Face NER token classification model to extract canonical skills and experience spans.', technologies: ['Python', 'Hugging Face', 'FastAPI', 'Qdrant'], duration: '7 Months', impact: 'Automated 80% of profile indexing.' }
    ],
    certifications: [
      { name: 'DeepLearning.AI Generative AI with LLMs', issuer: 'DeepLearning.AI / AWS', issueDate: '2023-06-20', credentialId: 'DLAI-GENAI-192', verificationStatus: 'VERIFIED' }
    ],
    careerPreferences: { desiredRoles: ['Head of AI / Chief Data Scientist'], targetSkills: ['Direct Preference Optimization (DPO)', 'Quantization (vLLM & GGUF)'], interestDomains: ['Enterprise GenAI Agents', 'Semantic Search'], willingToRelocate: false, preferredWorkMode: 'HYBRID' }
  },
  {
    code: 'EMP-IND-105',
    firstName: 'Vikram',
    lastName: 'Deshmukh',
    workEmail: 'vikram.deshmukh@company.com',
    designation: 'Engineering Manager & Solutions Architect',
    department: 'Engineering',
    location: 'Pune, MH (Hybrid)',
    headline: 'Engineering Manager & Solutions Architect | Ex-Infosys & Ola Cabs | System Design',
    summary: '11+ years leading 30+ engineer cross-functional teams, driving enterprise microservices architectures, and technical hiring.',
    totalExperienceYears: 11.5,
    currentLocation: 'Pune, Maharashtra, India',
    githubUrl: 'https://github.com/vikram-deshmukh',
    linkedinUrl: 'https://linkedin.com/in/vikram-deshmukh-eng',
    skills: [
      { name: 'System Architecture & Design', category: 'ARCHITECTURE', proficiency: 'Expert', yearsOfExperience: 9, source: 'MANAGER_VERIFIED', confidence: 0.99, verificationStatus: 'VERIFIED' },
      { name: 'Engineering Leadership & Mentorship', category: 'MANAGEMENT', proficiency: 'Expert', yearsOfExperience: 7, source: 'MANAGER_VERIFIED', confidence: 0.98, verificationStatus: 'VERIFIED' },
      { name: 'Java & Spring Boot', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 10, source: 'SELF_REPORTED', confidence: 0.96, verificationStatus: 'VERIFIED' },
      { name: 'Microservices Design Patterns', category: 'ARCHITECTURE', proficiency: 'Expert', yearsOfExperience: 8, source: 'MANAGER_VERIFIED', confidence: 0.97, verificationStatus: 'VERIFIED' }
    ],
    experience: [
      { title: 'Senior Engineering Manager', company: 'Ola Mobility', location: 'Bangalore, KA', startDate: '2019-07-01', endDate: '2023-06-30', current: false, description: 'Managed 25 engineers across Driver Lifecycle and Payments squads.', technologies: ['Java', 'Spring Boot', 'Kafka', 'MySQL'] }
    ],
    projects: [
      { name: 'Nexus Platform Architecture Modernization', role: 'Engineering Manager', description: 'Led squad restructuring and microservice domain separation.', technologies: ['Architecture Review', 'System Design'], duration: '12 Months', impact: 'Accelerated velocity by 40%.' }
    ],
    certifications: [
      { name: 'TOGAF 9.2 Certified Enterprise Architect', issuer: 'The Open Group', issueDate: '2021-05-18', credentialId: 'TOGAF-92-10829', verificationStatus: 'VERIFIED' }
    ],
    careerPreferences: { desiredRoles: ['Director of Engineering', 'VP of Engineering'], targetSkills: ['Executive Leadership', 'Strategic Tech Roadmapping'], interestDomains: ['Engineering Excellence', 'High-Scale SaaS'], willingToRelocate: false, preferredWorkMode: 'HYBRID' }
  },

  // ─── 2. SENIOR & STAFF ENGINEERS (6 - 25) ─────────────────────────────────
  { code: 'EMP-IND-106', firstName: 'Rohan', lastName: 'Mehta', workEmail: 'rohan.mehta@company.com', designation: 'Senior Full Stack Developer', department: 'Engineering', location: 'Gurgaon, HR (Hybrid)', headline: 'Senior Full Stack Developer | Ex-CRED & PayU | Node.js, React & MongoDB', totalExperienceYears: 5.4, skills: [{ name: 'Node.js', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'MongoDB', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'TypeScript', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-107', firstName: 'Kavita', lastName: 'Pillai', workEmail: 'kavita.pillai@company.com', designation: 'Staff Data & Analytics Engineer', department: 'AI Research & Data', location: 'Bangalore, KA (Hybrid)', headline: 'Staff Data Engineer | Ex-Jio Platforms & Ola | Spark, dbt & Snowflake', totalExperienceYears: 8.0, skills: [{ name: 'Apache Spark', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Python', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'Snowflake', category: 'DATABASE', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'dbt', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-108', firstName: 'Sneha', lastName: 'Reddy', workEmail: 'sneha.reddy@company.com', designation: 'Lead QA & Automation Engineer', department: 'Quality Engineering', location: 'Hyderabad, TS (Hybrid)', headline: 'Lead QA & Automation Engineer | Ex-PhonePe & Tech Mahindra | Cypress & Playwright', totalExperienceYears: 6.2, skills: [{ name: 'Playwright', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Cypress', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'API Automation', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'k6 Performance Testing', category: 'QA_TESTING', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-109', firstName: 'Siddharth', lastName: 'Nair', workEmail: 'siddharth.nair@company.com', designation: 'Staff Backend Engineer', department: 'Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Staff Backend Engineer | Ex-InMobi | High-Throughput Java & Distributed Caches', totalExperienceYears: 7.8, skills: [{ name: 'Java 17', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'Spring Boot', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Aerospike', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Kafka', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-110', firstName: 'Meera', lastName: 'Nambiar', workEmail: 'meera.nambiar@company.com', designation: 'Senior Product Designer', department: 'Product & Design', location: 'Bangalore, KA (Hybrid)', headline: 'Senior Product Designer | Ex-Urban Company & Meesho | Design Systems & UX Research', totalExperienceYears: 6.5, skills: [{ name: 'Figma & Design Systems', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'UX Research & Wireframing', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Prototyping & Micro-interactions', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-111', firstName: 'Karthik', lastName: 'Subramanian', workEmail: 'karthik.subramanian@company.com', designation: 'Senior Cloud Security Architect', department: 'Platform & DevOps', location: 'Chennai, TN (Hybrid)', headline: 'Senior Cloud Security Architect | Ex-Zoho & Wipro | IAM, Zero-Trust & Vault', totalExperienceYears: 8.2, skills: [{ name: 'Cloud Security (AWS/Azure)', category: 'SECURITY', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'HashiCorp Vault', category: 'SECURITY', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'IAM & RBAC Governance', category: 'SECURITY', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'Kubernetes Hardening', category: 'SECURITY', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-112', firstName: 'Pooja', lastName: 'Chopra', workEmail: 'pooja.chopra@company.com', designation: 'Senior Data Scientist', department: 'AI Research & Data', location: 'Gurgaon, HR (Hybrid)', headline: 'Senior Data Scientist | Ex-Makemytrip & Fractal | Predictive Modeling & Pricing ML', totalExperienceYears: 5.8, skills: [{ name: 'Python & Scikit-Learn', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'XGBoost & LightGBM', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'SQL & Feature Stores', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'MLflow & MLOps', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-113', firstName: 'Aditya', lastName: 'Kulkarni', workEmail: 'aditya.kulkarni@company.com', designation: 'Senior React Native Mobile Engineer', department: 'Engineering', location: 'Pune, MH (Hybrid)', headline: 'Senior Mobile Engineer | Ex-Zepto & Dunzo | React Native & Offline First Architecture', totalExperienceYears: 6.0, skills: [{ name: 'React Native', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'TypeScript', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'iOS/Android Native Bridges', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Redux Toolkit', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-114', firstName: 'Divya', lastName: 'Bose', workEmail: 'divya.bose@company.com', designation: 'Staff SRE Engineer', department: 'Platform & DevOps', location: 'Bangalore, KA (Hybrid)', headline: 'Staff SRE Engineer | Ex-Delhivery | Incident Response, Chaos Testing & Observability', totalExperienceYears: 7.5, skills: [{ name: 'Prometheus & Grafana', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'OpenTelemetry', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Linux Kernel Tuning', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'Chaos Engineering', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-115', firstName: 'Harsh', lastName: 'Vardhan', workEmail: 'harsh.vardhan@company.com', designation: 'Senior Golang Backend Engineer', department: 'Engineering', location: 'Noida, UP (Hybrid)', headline: 'Senior Golang Engineer | Ex-Paytm Payments Bank | Low Latency APIs & Microservices', totalExperienceYears: 5.2, skills: [{ name: 'Go (Golang)', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'gRPC', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'MySQL High Availability', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Docker', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-116', firstName: 'Ritu', lastName: 'Singhania', workEmail: 'ritu.singhania@company.com', designation: 'Staff NLP Researcher', department: 'AI Research & Data', location: 'Bangalore, KA (Hybrid)', headline: 'Staff NLP Researcher | Ex-Wadhwani AI | LLM Fine-Tuning & Indic Language NLP', totalExperienceYears: 7.0, skills: [{ name: 'PyTorch', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Hugging Face Transformers', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'LoRA & PEFT Fine-Tuning', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'Tokenization & Embeddings', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-117', firstName: 'Abhishek', lastName: 'Tripathi', workEmail: 'abhishek.tripathi@company.com', designation: 'Principal Database Architect', department: 'Engineering', location: 'Hyderabad, TS (Hybrid)', headline: 'Principal Database Architect | Ex-Oracle India & TCS | PostgreSQL & CockroachDB', totalExperienceYears: 10.0, skills: [{ name: 'PostgreSQL Internals & Tuning', category: 'DATABASE', proficiency: 'Expert', yearsOfExperience: 9, verificationStatus: 'VERIFIED' }, { name: 'CockroachDB & Distributed SQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Database Sharding & Replication', category: 'DATABASE', proficiency: 'Expert', yearsOfExperience: 8, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-118', firstName: 'Neelam', lastName: 'Pandey', workEmail: 'neelam.pandey@company.com', designation: 'Senior Frontend Engineer', department: 'Engineering', location: 'Gurgaon, HR (Hybrid)', headline: 'Senior Frontend Engineer | Ex-Cars24 | Vue.js, React & Micro-frontends', totalExperienceYears: 4.8, skills: [{ name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Vue.js 3', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'CSS Animation & Tailwind', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'JavaScript ESNext', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-119', firstName: 'Varun', lastName: 'Garg', workEmail: 'varun.garg@company.com', designation: 'Lead FinTech Solutions Engineer', department: 'Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Lead Solutions Engineer | Ex-Cashfree | Payment Gateways & Banking Integrations', totalExperienceYears: 6.8, skills: [{ name: 'Java', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'ISO 8583 & UPI Protocols', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'PostgreSQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'PCI-DSS Compliance', category: 'SECURITY', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-120', firstName: 'Shweta', lastName: 'Bhardwaj', workEmail: 'shweta.bhardwaj@company.com', designation: 'Lead Product Manager (Platform)', department: 'Product & Design', location: 'Bangalore, KA (Hybrid)', headline: 'Lead Platform PM | Ex-Freshworks | Developer Portals & API Products', totalExperienceYears: 7.2, skills: [{ name: 'Product Strategy & Roadmaps', category: 'MANAGEMENT', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'API Product Management', category: 'MANAGEMENT', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Agile & Jira Execution', category: 'MANAGEMENT', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-121', firstName: 'Manish', lastName: 'Gupta', workEmail: 'manish.gupta@company.com', designation: 'Senior Data Platform Engineer', department: 'AI Research & Data', location: 'Pune, MH (Hybrid)', headline: 'Senior Data Engineer | Ex-Bajaj Finserv | Apache Kafka, Flink & Big Data', totalExperienceYears: 5.5, skills: [{ name: 'Apache Flink & Streaming', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Apache Kafka', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Scala / Java', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Hadoop & Hive', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-122', firstName: 'Deepika', lastName: 'Rao', workEmail: 'deepika.rao@company.com', designation: 'Senior QA Automation SDET', department: 'Quality Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Senior SDET | Ex-Swiggy Instamart | Mobile & Web Automation Testing', totalExperienceYears: 5.1, skills: [{ name: 'Appium Mobile Testing', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Selenium WebDriver', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Java TestNG Framework', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'RestAssured API Testing', category: 'QA_TESTING', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-123', firstName: 'Tarun', lastName: 'Saxena', workEmail: 'tarun.saxena@company.com', designation: 'Senior Backend Developer (Python)', department: 'Engineering', location: 'Noida, UP (Hybrid)', headline: 'Senior Backend Developer | Ex-PolicyBazaar | Django, FastAPI & Celery', totalExperienceYears: 4.9, skills: [{ name: 'Python', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'FastAPI & Django', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Celery & RabbitMQ', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Redis', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-124', firstName: 'Ishita', lastName: 'Roy', workEmail: 'ishita.roy@company.com', designation: 'Staff Data Analyst & BI Lead', department: 'AI Research & Data', location: 'Kolkata / Bangalore', headline: 'Staff Data Analyst | Ex-PwC India | PowerBI, Tableau & Executive Analytics', totalExperienceYears: 6.8, skills: [{ name: 'PowerBI & DAX', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Advanced SQL & Data Modeling', category: 'DATABASE', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Tableau', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Python for Analytics', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-125', firstName: 'Nitin', lastName: 'Agarwal', workEmail: 'nitin.agarwal@company.com', designation: 'Senior DevOps & Terraform Engineer', department: 'Platform & DevOps', location: 'Gurgaon, HR (Hybrid)', headline: 'Senior DevOps Engineer | Ex-Snapdeal | Terraform, GCP & GitHub Actions', totalExperienceYears: 5.6, skills: [{ name: 'Terraform', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Google Cloud Platform (GCP)', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Kubernetes', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Helm Package Manager', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },

  // ─── 3. MID-LEVEL & SPECIALIST ENGINEERS (26 - 45) ────────────────────────
  { code: 'EMP-IND-126', firstName: 'Sanya', lastName: 'Malhotra', workEmail: 'sanya.malhotra@company.com', designation: 'Frontend Software Engineer', department: 'Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Frontend Engineer | React, TypeScript & Responsive Glass UI', totalExperienceYears: 3.5, skills: [{ name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'TypeScript', category: 'FRONTEND', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'CSS3 & Vanilla Styling', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-127', firstName: 'Prateek', lastName: 'Mishra', workEmail: 'prateek.mishra@company.com', designation: 'Backend Engineer (Node.js)', department: 'Engineering', location: 'Pune, MH (Hybrid)', headline: 'Backend Engineer | Express, TypeScript & MongoDB Aggregation', totalExperienceYears: 3.2, skills: [{ name: 'Node.js & Express', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'MongoDB', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'REST APIs', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-128', firstName: 'Tanvi', lastName: 'Desai', workEmail: 'tanvi.desai@company.com', designation: 'Associate AI Engineer', department: 'AI Research & Data', location: 'Pune, MH (Hybrid)', headline: 'Associate AI Engineer | Ex-TCS Research | Vector Search & RAG Pipelines', totalExperienceYears: 2.8, skills: [{ name: 'Python', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'LangChain & LlamaIndex', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'Qdrant Vector DB', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 1, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-129', firstName: 'Gaurav', lastName: 'Bhatia', workEmail: 'gaurav.bhatia@company.com', designation: 'DevOps & CI/CD Engineer', department: 'Platform & DevOps', location: 'Noida, UP (Hybrid)', headline: 'DevOps Engineer | Docker, GitHub Actions, AWS EC2 & Monitoring', totalExperienceYears: 3.8, skills: [{ name: 'Docker', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'GitHub Actions', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'AWS Cloud Services', category: 'CLOUD_DEVOPS', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-130', firstName: 'Megha', lastName: 'Joshi', workEmail: 'megha.joshi@company.com', designation: 'QA Automation Engineer', department: 'Quality Engineering', location: 'Hyderabad, TS (Hybrid)', headline: 'QA Engineer | Cypress, Postman API & Supertest', totalExperienceYears: 3.0, skills: [{ name: 'Cypress Test Automation', category: 'QA_TESTING', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Postman API Testing', category: 'QA_TESTING', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'JavaScript', category: 'FRONTEND', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-131', firstName: 'Karan', lastName: 'Kapoor', workEmail: 'karan.kapoor@company.com', designation: 'Full Stack Engineer', department: 'Engineering', location: 'Gurgaon, HR (Hybrid)', headline: 'Full Stack Engineer | React, Node.js & PostgreSQL', totalExperienceYears: 3.6, skills: [{ name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Node.js', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'PostgreSQL', category: 'DATABASE', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-132', firstName: 'Rashmi', lastName: 'Kashyap', workEmail: 'rashmi.kashyap@company.com', designation: 'Cloud Infrastructure Engineer', department: 'Platform & DevOps', location: 'Bangalore, KA (Hybrid)', headline: 'Cloud Infrastructure Engineer | AWS IAM, VPC, S3 & EKS', totalExperienceYears: 4.2, skills: [{ name: 'AWS Cloud Architecture', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Kubernetes', category: 'CLOUD_DEVOPS', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'Terraform', category: 'CLOUD_DEVOPS', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-133', firstName: 'Mayank', lastName: 'Saxena', workEmail: 'mayank.saxena@company.com', designation: 'Data Analytics Engineer', department: 'AI Research & Data', location: 'Hyderabad, TS (Hybrid)', headline: 'Data Engineer | Python, SQL, Airflow & Data Pipelines', totalExperienceYears: 3.4, skills: [{ name: 'Python', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'SQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Apache Airflow', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-134', firstName: 'Bhavna', lastName: 'Sethi', workEmail: 'bhavna.sethi@company.com', designation: 'Associate Product Manager', department: 'Product & Design', location: 'Gurgaon, HR (Hybrid)', headline: 'Associate PM | Feature Roadmapping & User Experience Analytics', totalExperienceYears: 3.0, skills: [{ name: 'Agile & Scrum', category: 'MANAGEMENT', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'User Story Mapping', category: 'MANAGEMENT', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'SQL Analysis', category: 'DATABASE', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-135', firstName: 'Deepak', lastName: 'Chauhan', workEmail: 'deepak.chauhan@company.com', designation: 'Security & Compliance Analyst', department: 'Platform & DevOps', location: 'Chennai, TN (Hybrid)', headline: 'Security Analyst | SOC2, ISO27001 & Vulnerability Assessments', totalExperienceYears: 4.0, skills: [{ name: 'Vulnerability Scanning (SAST/DAST)', category: 'SECURITY', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'SOC2 Compliance', category: 'SECURITY', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Linux Security', category: 'SECURITY', proficiency: 'Intermediate', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-136', firstName: 'Swati', lastName: 'Ranjan', workEmail: 'swati.ranjan@company.com', designation: 'Backend Software Developer (Go)', department: 'Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Golang Engineer | Microservices & gRPC Internal Systems', totalExperienceYears: 3.5, skills: [{ name: 'Go (Golang)', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'gRPC', category: 'BACKEND', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'PostgreSQL', category: 'DATABASE', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-137', firstName: 'Ankit', lastName: 'Trivedi', workEmail: 'ankit.trivedi@company.com', designation: 'Frontend Engineer (React & TypeScript)', department: 'Engineering', location: 'Pune, MH (Hybrid)', headline: 'React Developer | State Management & Design Systems', totalExperienceYears: 3.3, skills: [{ name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'TypeScript', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }, { name: 'Tailwind CSS', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-138', firstName: 'Monika', lastName: 'Patel', workEmail: 'monika.patel@company.com', designation: 'Lead Data Governance Specialist', department: 'AI Research & Data', location: 'Ahmedabad / Bangalore', headline: 'Data Governance Lead | Data Catalogs, GDPR & Lineage Tracking', totalExperienceYears: 6.5, skills: [{ name: 'Data Governance & Catalogs', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Data Lineage & dbt', category: 'DATA_AI', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Enterprise SQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-139', firstName: 'Suresh', lastName: 'Menon', workEmail: 'suresh.menon@company.com', designation: 'Senior Mobile Engineer (Flutter)', department: 'Engineering', location: 'Kochi / Bangalore', headline: 'Flutter Mobile Engineer | Cross-Platform iOS & Android Apps', totalExperienceYears: 5.0, skills: [{ name: 'Flutter & Dart', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'BLoC State Management', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'REST APIs & WebSockets', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-140', firstName: 'Kritika', lastName: 'Bansal', workEmail: 'kritika.bansal@company.com', designation: 'Performance & Load Test Engineer', department: 'Quality Engineering', location: 'Gurgaon, HR (Hybrid)', headline: 'Performance QA Engineer | k6, JMeter & Distributed Load Generation', totalExperienceYears: 4.5, skills: [{ name: 'k6 Performance Testing', category: 'QA_TESTING', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Apache JMeter', category: 'QA_TESTING', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Grafana Dashboards', category: 'CLOUD_DEVOPS', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-141', firstName: 'Naveen', lastName: 'Choudhary', workEmail: 'naveen.choudhary@company.com', designation: 'Staff Network & Infrastructure Engineer', department: 'Platform & DevOps', location: 'Bangalore, KA (Hybrid)', headline: 'Network Architect | VPC Peering, Direct Connect & VPN Gateways', totalExperienceYears: 8.5, skills: [{ name: 'Cloud Networking & VPCs', category: 'CLOUD_DEVOPS', proficiency: 'Expert', yearsOfExperience: 8, verificationStatus: 'VERIFIED' }, { name: 'BGP Routing & Firewalls', category: 'SECURITY', proficiency: 'Expert', yearsOfExperience: 7, verificationStatus: 'VERIFIED' }, { name: 'AWS CloudFormation', category: 'CLOUD_DEVOPS', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-142', firstName: 'Simran', lastName: 'Ahluwalia', workEmail: 'simran.ahluwalia@company.com', designation: 'UI/UX Visual Interaction Designer', department: 'Product & Design', location: 'Noida, UP (Hybrid)', headline: 'Interaction Designer | Micro-Animations, Glass UI & Dark Mode', totalExperienceYears: 4.2, skills: [{ name: 'Figma UI Design', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Interactive Prototyping', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Design Systems', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-143', firstName: 'Vivek', lastName: 'Dubey', workEmail: 'vivek.dubey@company.com', designation: 'Senior Big Data Engineer', department: 'AI Research & Data', location: 'Hyderabad, TS (Hybrid)', headline: 'Big Data Engineer | Spark, Scala, Hive & Data Pipeline Orchestration', totalExperienceYears: 5.9, skills: [{ name: 'Apache Spark', category: 'DATA_AI', proficiency: 'Expert', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Scala Programming', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'Delta Lake', category: 'DATA_AI', proficiency: 'Intermediate', yearsOfExperience: 2, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-144', firstName: 'Pallavi', lastName: 'Gokhale', workEmail: 'pallavi.gokhale@company.com', designation: 'Frontend Engineer (React Ecosystem)', department: 'Engineering', location: 'Pune, MH (Hybrid)', headline: 'React Frontend Developer | Modern Component Architecture', totalExperienceYears: 3.7, skills: [{ name: 'React.js', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'Redux / Zustand', category: 'FRONTEND', proficiency: 'Advanced', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }, { name: 'CSS Grid & Flexbox', category: 'FRONTEND', proficiency: 'Expert', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }] },
  { code: 'EMP-IND-145', firstName: 'Alok', lastName: 'Srivastava', workEmail: 'alok.srivastava@company.com', designation: 'Senior Backend Engineer (Java & Kafka)', department: 'Engineering', location: 'Bangalore, KA (Hybrid)', headline: 'Senior Java Backend Engineer | Spring Boot, Microservices & Kafka', totalExperienceYears: 6.2, skills: [{ name: 'Java & Spring Boot', category: 'BACKEND', proficiency: 'Expert', yearsOfExperience: 6, verificationStatus: 'VERIFIED' }, { name: 'Apache Kafka', category: 'BACKEND', proficiency: 'Advanced', yearsOfExperience: 4, verificationStatus: 'VERIFIED' }, { name: 'PostgreSQL', category: 'DATABASE', proficiency: 'Advanced', yearsOfExperience: 5, verificationStatus: 'VERIFIED' }, { name: 'Redis', category: 'DATABASE', proficiency: 'Intermediate', yearsOfExperience: 3, verificationStatus: 'VERIFIED' }] }
];
