export default {
  CLOCKED_IN: 'ATTENDANCE.CLOCKED_IN',
  CLOCKED_OUT: 'ATTENDANCE.CLOCKED_OUT',
  STATUS_CHANGED: 'ATTENDANCE.STATUS_CHANGED',
  REGULARIZATION_REQUESTED: 'ATTENDANCE.REGULARIZATION_REQUESTED',
  REGULARIZATION_APPROVED: 'ATTENDANCE.REGULARIZATION_APPROVED',
  REGULARIZATION_REJECTED: 'ATTENDANCE.REGULARIZATION_REJECTED',
  FINALIZED: 'ATTENDANCE.FINALIZED',
  LOCKED: 'ATTENDANCE.LOCKED',
  PAY_PERIOD_FINALIZED: 'ATTENDANCE.PAY_PERIOD_FINALIZED',
  RECONCILIATION_COMPLETED: 'ATTENDANCE.RECONCILIATION_COMPLETED',
  RECORD_RECONCILED: 'ATTENDANCE.RECORD_RECONCILED',
  PAYROLL_PROCESSING_STARTED: 'ATTENDANCE.PAYROLL_PROCESSING_STARTED',
  PAYROLL_PROCESSED: 'ATTENDANCE.PAYROLL_PROCESSED',
  PAYROLL_LOCKED: 'ATTENDANCE.PAYROLL_LOCKED',
  PAYROLL_STATE_VALIDATION_FAILED: 'ATTENDANCE.PAYROLL_STATE_VALIDATION_FAILED',
  CONFLICT_RESOLVED: 'ATTENDANCE.CONFLICT_RESOLVED'
};
