export default {
  CREATED: 'EMPLOYEE.CREATED',
  UPDATED: 'EMPLOYEE.UPDATED',
  STATUS_CHANGED: 'EMPLOYEE.STATUS_CHANGED',
  MANAGER_CHANGED: 'EMPLOYEE.MANAGER_CHANGED',
  INVITED: 'EMPLOYEE.INVITED',
  USER_LINKED: 'EMPLOYEE.USER_LINKED',
  ARCHIVED: 'EMPLOYEE.ARCHIVED',
  RESTORED: 'EMPLOYEE.RESTORED'
};
