export const PAYROLL_EVENTS = {
  CYCLE_CREATED: 'PAYROLL.CYCLE_CREATED',
  CYCLE_STATUS_CHANGED: 'PAYROLL.CYCLE_STATUS_CHANGED',
  STRUCTURE_CREATED: 'PAYROLL.STRUCTURE_CREATED',
  REVISION_CREATED: 'PAYROLL.REVISION_CREATED',
  RUN_STARTED: 'PAYROLL.RUN_STARTED',
  RUN_COMPLETED: 'PAYROLL.RUN_COMPLETED',
  RUN_FAILED: 'PAYROLL.RUN_FAILED',
  RUN_LOCKED: 'PAYROLL.RUN_LOCKED',
  PAYSLIPS_GENERATED: 'PAYROLL.PAYSLIPS_GENERATED',
  PAYSLIP_FINALIZED: 'PAYROLL.PAYSLIP_FINALIZED'
};

export default PAYROLL_EVENTS;
